gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/data/small.tsv
block_size:
  44
out_file:
  /Users/krsc0813/CLionProjects/gwas_local/data/small.tsv.grlz
query_coordinates:
  1:693731-758144,1:799499-838732
codecs:
  zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib