gwas_file:
  /Users/krsc0813/Desktop/gwas/pan_ukbb/continuous-22409-both_sexes-irnt.tsv

block_size:
  20000

out_directory:
  ukbb_block20000_zlib

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.bed
  pval:
    None
  other:
    0.2
  uncertainty:
    1-e8

extra_indices:
  None

codecs:
  int:
    zlib
  float:
    zlib
  string:
    zlib