gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.tsv

block_size:
  10

out_directorys:
  kristen_out

query:
    genomic:
      /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.bed
    pval:
      0.5
    other:
      0.2
    uncertainty:
      1-e8

extra_indices:
    pval, other, uncertainty

codecs:
  int:
    zlib
  float:
    zlib
  string:
    zlib