gwas_file:
  /Users/krsc0813/Desktop/gwas/pan_ukbb/continuous-22409-both_sexes-irnt.tsv

block_size:
  10000

out_name:
  combo

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.bed
  pval:
    NA
  other:
    None
  uncertainty:
    None

extra_indices:
  None

codecs:
  int:
    zstd
  float:
    bz2
  string:
    zlib