gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.tsv

block_size:
  map_files/test.map

out_name:
  xz

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.bed
  col_idx:
    8
  bins:
    5e-1, 5e-5, 5.1e-8
  threshold:
    <= 5e-8

extra_indices:
  pval

codecs:
  int:
    xz
  float:
    xz
  string:
    xz