gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.tsv

block_size:
  5

out_name:
  bz2

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.bed
  col_idx:
    8
  bins:
    5e-1, 5e-5, 5.1e-8
  threshold:
    <= 5e-8

extra_indices:
  pval

codecs:
  int:
    bz2
  float:
    bz2
  string:
    bz2