gwas_file:
  gwas_files/test.tsv
block_size:
  map_files/test.map
query_type:
  coordinate
query_coordinate:
  2:100-150000
query_statistic:
  p_value:0.3
codecs:
  zstd,zstd,zstd,zstd,zstd,zstd,zstd,zstd,zstd,zstd