gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.tsv

block_size:
  5

out_name:
  bz2

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.bed
  col_idx:
    8
  bins:
    0.3, 4.3, 7.29
  threshold:
    >= 7.3

extra_index:
  pval

codecs:
  int:
    bz2
  float:
    bz2
  string:
    bz2