gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/continuous-30130-both_sexes-irnt.tsv

block_size:
  2000

out_name:
  zlib

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/hg19.protein_coding.bed
  col_idx:
    7
  bins:
    0.3, 4.3, 7.29
  threshold:
    >= 7.3

extra_index:
  pval

codecs:
  int:
    zlib
  float:
    zlib
  string:
    zlib