gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/phecode-473-both_sexes.tsv

block_size:
  2000

out_name:
  bz2

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/hg19.protein_coding.bed
  col_idx:
    19
  bins:
    0.3, 4.3, 7.29
  threshold:
    >= 7.3

extra_index:
  pval

codecs:
  int:
    bz2
  float:
    bz2
  string:
    bz2
