gwas_file:
  /Users/krsc0813/Desktop/gwas/pan_ukbb/continuous-22409-both_sexes-irnt.tsv

block_size:
  10000

out_name:
  zstd

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/hg19.protein_coding.bed
  col_idx:
    7
  bins:
    5e-1, 5e-5, 5.1e-8
  threshold:
    <= 5e-8

extra_indices:
  pval

codecs:
  int:
    zstd
  float:
    zstd
  string:
    zstd