gwas_file:
  /Users/krsc0813/Desktop/gwas/pan_ukbb/continuous-22409-both_sexes-irnt.tsv

block_size:
  10000

out_name:
  zstd

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/ukbb.bed
  pval:
    1e-8
  other:
    None
  uncertainty:
    None

extra_indices:
  pval

codecs:
  int:
    zstd
  float:
    zstd
  string:
    zstd