gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/continuous-103220-both_sexes.tsv

block_size:
  10000

out_name:
  bz2

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/hg19.protein_coding.bed
  col_idx:
    7
  bins:
    0.3, 4.3, 7.29
  threshold:
    >= 7.3

extra_indices:
  pval

codecs:
  int:
    bz2
  float:
    bz2
  string:
    bz2