gwas_file:
  /Users/krsc0813/Desktop/gwas/pan_ukbb/continuous-22409-both_sexes-irnt.tsv

block_size:
  15000

out_name:
  fpfvb-xz

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/test.bed
  pval:
    NA
  other:
    None
  uncertainty:
    None

extra_indices:
  None

codecs:
  int:
    fpfVB
  float:
    xz
  string:
    xz