gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/phecode-473-both_sexes.tsv

block_size:
  10000

out_name:
  xz

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/hg19.protein_coding.bed
  col_idx:
    19
  bins:
    5e-1, 5e-5, 5.1e-8
  threshold:
    <= 5e-8

extra_indices:
  pval

codecs:
  int:
    xz
  float:
    xz
  string:
    xz