gwas_file:
  /Users/krsc0813/Desktop/gwas/pan_ukbb/ukbb_22409/continuous-22409-both_sexes-irnt.tsv

block_size:
  map_files/chrm_1-22.map

out_name:
  deflate

query:
  genomic:
    /Users/krsc0813/CLionProjects/gwas_local/gwas_files/ukbb.bed
  col_idx:
    7
  bins:
    5e-1, 5e-5, 5.1e-8
  threshold:
    <= 5e-8

extra_indices:
  pval

codecs:
  int:
    deflate
  float:
    deflate
  string:
    deflate