gwas_file:
  /Users/krsc0813/CLionProjects/gwas_local/gwas_files/GCST90179150_buildGRCh37.tsv
block_size:
  20000
map:
  /Users/krsc0813/CLionProjects/gwas_local/map_files/chrm_1-22.map
query_type:
  coordinate
query_coordinate:
  1:693731-758144,1:798900-845000,18:65659994-67800000
query_statistic:
  p_value:0.05
codecs:
  zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib